### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_text'

### ISSUE THREAD

**Issue by Bunkai9448** [tongyuantongyu/WebNovelCrawler#4]
I'm doing it under 
 Ubuntu 20.04 LTS
 Python 3.8.10, with the extra libs required 

Running command `python3 kakuyomu.py`
 `[Initial] Input novel id here: kakuyomu.jp/works/1177354054880254749`
 
And it gives me this error/trace:
```
[Main Thread] Fetching Metadata...
Traceback (most recent call last):
  File "kakuyomu.py", line 192, in <module>
    syo.get_meta()
  File "kakuyomu.py", line 112, in get_meta
    self.novel_title = self.metapage.find('span', id='catchphrase-body').get_text()
AttributeError: 'NoneType' object has no attribute 'get_text'
```

**Comment by samjaninf** [comment]
It's a time out issue. I suspect 16 threads is too fast so you get a 429 in there sometimes.

**Comment by Bunkai9448** [comment]
I got everything working thanks to someone from a discord server I'm in. I pushed a commit to fix the issue
(with a copied and edited file to have both options). 

Until that is approved, you can find the fix in my fork: https://github.com/Bunkai9448/WebNovelCrawler/
